services:
  mcp-server:
    build:
      context: .
      dockerfile: mcp-server/Dockerfile
    ports:
      - "5000:5000"
    container_name: mcp-server

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - mcp-server
    container_name: frontend-server
